# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kconnect < Formula
  desc "Kubernetes Connection Manager CLI"
  homepage "https://github.com/fidelity/kconnect"
  version "0.5.23"

  depends_on "Azure/kubelogin/kubelogin"
  depends_on "aws-iam-authenticator"
  depends_on "kubernetes-cli"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fidelity/kconnect/releases/download/0.5.23/kconnect_macos_amd64.tar.gz"
      sha256 "defdc41eb0b7e175781046f13479edc52b191ce8dc9175a6260dcdfff2965298"

      define_method(:install) do
        bin.install "kconnect"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fidelity/kconnect/releases/download/0.5.23/kconnect_macos_arm64.tar.gz"
      sha256 "77710da0b457f24754e97fea57a1d38e95420215b7d7bbc8d8ce30f1d593ff24"

      define_method(:install) do
        bin.install "kconnect"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fidelity/kconnect/releases/download/0.5.23/kconnect_linux_amd64.tar.gz"
      sha256 "b39c4773b431aed1dc0577f8a37a1c1eb19e345ab136b64fc691442b53a00155"
      define_method(:install) do
        bin.install "kconnect"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fidelity/kconnect/releases/download/0.5.23/kconnect_linux_arm64.tar.gz"
      sha256 "739fbc09ed9ecfef6f518b8f5e9c10d33ca3012a1af8cd38a8d4a75f7ffa6ab2"
      define_method(:install) do
        bin.install "kconnect"
      end
    end
  end
end
