# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kconnect < Formula
  desc "Kubernetes Connection Manager CLI"
  homepage "https://github.com/fidelity/kconnect"
  version "0.5.23-rc.1"

  depends_on "Azure/kubelogin/kubelogin"
  depends_on "aws-iam-authenticator"
  depends_on "kubernetes-cli"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fidelity/kconnect/releases/download/0.5.23-rc.1/kconnect_macos_amd64.tar.gz"
      sha256 "1fdd999ea32b69873ed93df6b6bc2b330eb76ca1a0d29bafd9e2e49a94190580"

      define_method(:install) do
        bin.install "kconnect"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fidelity/kconnect/releases/download/0.5.23-rc.1/kconnect_macos_arm64.tar.gz"
      sha256 "73ee3f8e74253aaf74e16e31c3cd1e45e2d69e4bf8d36512b73a4aa63c0e075a"

      define_method(:install) do
        bin.install "kconnect"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fidelity/kconnect/releases/download/0.5.23-rc.1/kconnect_linux_amd64.tar.gz"
      sha256 "44fedc47e1ee96ec56fd55ff71eb9923a488842076b7c21c1f277e980b6b3a3d"
      define_method(:install) do
        bin.install "kconnect"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fidelity/kconnect/releases/download/0.5.23-rc.1/kconnect_linux_arm64.tar.gz"
      sha256 "960319007bf95b0bf19a31fe943993f9a9b92ebc24713bb382ec84bbd615e06d"
      define_method(:install) do
        bin.install "kconnect"
      end
    end
  end
end
